SELECT * FROM EMPLOYEE WHERE '2017-12-28' BETWEEN BEGIN_DATE AND END_DATE;
SELECT * FROM EMPLOYEE WHERE '2017-12-28' <= END_DATE;
SELECT ID, NAME, SUPERVISOR as sup_id, BEGIN_DATE, END_DATE, (SELECT NAME FROM EMPLOYEE WHERE ID = sup_id) as SUPERVISOR_NAME FROM EMPLOYEE WHERE ID = 6;
